# Generated by Django 3.2.5 on 2021-07-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extract_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
                ('descriptor', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_id',
        ),
    ]
