# Generated by Django 3.2.5 on 2021-07-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extract_Feature',
        ),
    ]
