# Generated by Django 3.2.5 on 2021-07-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_delete_extract_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
                ('descriptor', models.JSONField()),
            ],
        ),
    ]
