# Generated by Django 3.2.5 on 2021-07-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_extractfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractfeature',
            name='descriptor',
            field=models.TextField(),
        ),
    ]
