# Generated by Django 3.2.5 on 2021-07-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_temporaryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user_id',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
