# Generated by Django 3.2.5 on 2021-07-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_image_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='object_3D',
            field=models.ImageField(default='Object3D/obj', upload_to='Object3D/'),
            preserve_default=False,
        ),
    ]
