# Generated by Django 3.2.5 on 2021-07-28 07:24

from django.db import migrations, models
import playground.models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_alter_image_object_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='object_3D',
            field=models.FileField(upload_to=playground.models.Image.get_file_path),
        ),
    ]
