# Generated by Django 3.2.5 on 2021-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_alter_image_object_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='object_3D',
            field=models.FileField(upload_to='Object3D/a3f54ebd-0a77-46ed-99b0-7d7f1831cc12/'),
        ),
    ]
