# Generated by Django 3.2.5 on 2021-07-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_auto_20210728_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='mtl',
            field=models.FileField(upload_to='Object3D/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='object_3D',
            field=models.FileField(upload_to='Object3D/'),
        ),
    ]
