# Generated by Django 3.2.5 on 2021-07-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0018_auto_20210728_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractFeature',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
